//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Flash.rc
//
#define IDS_CANNOT_OPEN_FLASHFILE       5
#define IDS_NEW_FLASHFILE               7
#define IDD_ABOUTBOX                    100
#define IDC_EDIT1                       101
#define IDC_EDIT2                       102
#define IDC_EDIT3                       103
#define IDC_STATIC1                     104
#define IDD_DIALOG1                     105
#define IDC_STATIC2                     106
#define IDD_DIALOG2                     106
#define IDC_STATIC3                     107
#define IDM_INTRO                       110
#define IDC_EDITQuestion                111
#define IDC_EDITAnswer                  112
#define IDC_Question                    114
#define IDC_Answer                      115
#define IDD_MultipleChoice              115
#define IDC_EDITNEW                     116
#define IDD_ShowAnswer                  116
#define IDC_EditPrior                   117
#define IDD_MCShowCorrect               117
#define IDC_EditNext                    118
#define IDD_TypeInAnswer                118
#define IDC_EditApply                   119
#define IDC_EditDel                     120
#define IDC_EDITATTEMPTS                121
#define IDC_MultipleChoiceList          126
#define IDR_MAINFRAME                   128
#define IDR_FLASHTYPE                   129
#define IDS_STRING129                   129
#define IDR_MAINFRAME1                  129
#define IDC_MultipleChoiceEditQ         130
#define IDC_Yes                         130
#define IDC_No                          131
#define IDC_ShowAnswer                  132
#define IDC_MultipleChoiceEditA         133
#define IDM_CLEARSTATS                  32771
#define IDM_MULTIPLECHOICE              32772
#define IDM_SHOWANSWER                  32773
#define IDM_TYPEINANSWER                32774
#define IDM_EDITFILE                    32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
